# Generated by Django 4.2.7 on 2023-12-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_image_verifications_alter_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='video-uploads/')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('date_uploaded', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='image-uploads/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
