# Generated by Django 4.2.7 on 2023-12-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_video_alter_image_image_alter_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='image_name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='video_name',
        ),
    ]
