# Generated by Django 4.2.7 on 2023-12-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0006_alter_image_date_uploaded_alter_video_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='heading',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='subheading',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
